/**
 * Replay-fixture finalizer (change addReplayReportBounds, task tk-86e9bd603c47).
 *
 * Sanitizes freshly-exported Temporal histories and writes the committed
 * history + metadata pairs consumed by `replay-determinism.test.ts`.
 *
 * Sanitization is intentionally minimal and replay-safe: only the per-worker
 * `identity` field (pid@hostname) is normalized to the established
 * `temporal-cli@replay-host` convention used by the existing fixture. Patch
 * markers, activity payloads, event types, and timestamps are preserved so the
 * committed history still replays deterministically via `Worker.runReplayHistory`.
 *
 * Regeneration flow (reproducible source recorded in each metadata `source`):
 *   1. REPLAY_FIXTURE_NAMESPACE=adv-replay-fixtures pnpm exec tsx scripts/gen-replay-fixture.ts --branch <branch>
 *   2. temporal workflow show --address 127.0.0.1:7233 --namespace "$REPLAY_FIXTURE_NAMESPACE" \
 *        --workflow-id <id> --output json --no-json-shorthand-payloads > raw.json
 *   3. pnpm exec tsx scripts/finalize-replay-fixture.ts --branch <branch> --raw raw.json
 *
 * Usage (all three, using the conventional /tmp raw paths):
 *   pnpm exec tsx scripts/finalize-replay-fixture.ts --all
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format as prettierFormat } from "prettier";

const SANITIZED_IDENTITY = "temporal-cli@replay-host";

const historiesDir = fileURLToPath(
  new URL("../src/temporal/__tests__/replay/histories/", import.meta.url),
);

type BranchId =
  | "state-backed-gate-artifact"
  | "state-backed-acceptance"
  | "acceptance-executive-summary"
  | "acceptance-readiness-fence"
  | "acceptance-readiness-fence-legacy";

interface FinalizeConfig {
  stem: string;
  workflowId: string;
  patchMarker?: string;
  name: string;
  covers: string[];
  source: string;
}

const GEN = "pnpm exec tsx scripts/gen-replay-fixture.ts";
const SHOW =
  'temporal workflow show --address 127.0.0.1:7233 --namespace "$REPLAY_FIXTURE_NAMESPACE" --output json --no-json-shorthand-payloads';

const CONFIGS: Record<BranchId, FinalizeConfig> = {
  "state-backed-gate-artifact": {
    stem: "addReplayReportBounds.state-backed-gate-artifact",
    workflowId:
      "adv/change/replay-fixture-project/replayFixtureStateBackedGateArtifact",
    patchMarker: "state-backed-gate-artifact-proof-v1",
    name: "addReplayReportBounds state-backed-gate-artifact",
    covers: [
      "STATE_BACKED_GATE_ARTIFACT_PROOF_PATCH (state-backed-gate-artifact-proof-v1): a new history completes the proposal gate via stateBackedArtifactEvidence, recording the patch marker and deriving artifact evidence from state.documents without disk inspection.",
      "Branch-specific coverage: non-acceptance artifact gate (proposal) takes the state-backed gate-artifact proof branch introduced for Temporal-only artifact storage.",
    ],
    source: `Controlled Temporal test-workflow history generated by \`${GEN} --branch state-backed-gate-artifact\` against a local dev server, exported with \`${SHOW} --workflow-id adv/change/replay-fixture-project/replayFixtureStateBackedGateArtifact\`, then sanitized (identity only). No event history hand-authored.`,
  },
  "state-backed-acceptance": {
    stem: "addReplayReportBounds.state-backed-acceptance",
    workflowId:
      "adv/change/replay-fixture-project/replayFixtureStateBackedAcceptance",
    patchMarker: "state-backed-acceptance-proof-v1",
    name: "addReplayReportBounds state-backed-acceptance",
    covers: [
      "STATE_BACKED_ACCEPTANCE_PROOF_PATCH (state-backed-acceptance-proof-v1): a new history completes the acceptance gate via stateBackedAcceptanceProof, recording the patch marker and materializing executive-summary.md and acceptance.md through writeArtifactActivity.",
      "Branch-specific coverage: acceptance gate takes the state-backed acceptance proof branch (completeStateBackedGate AC1/AC2/AC7) instead of disk inspection.",
    ],
    source: `Controlled Temporal test-workflow history generated by \`${GEN} --branch state-backed-acceptance\` against a local dev server, exported with \`${SHOW} --workflow-id adv/change/replay-fixture-project/replayFixtureStateBackedAcceptance\`, then sanitized (identity only). No event history hand-authored.`,
  },
  "acceptance-executive-summary": {
    stem: "addReplayReportBounds.acceptance-executive-summary",
    workflowId:
      "adv/change/replay-fixture-project/replayFixtureLegacyAcceptanceExecSummary",
    patchMarker: "acceptance-executive-summary-proof-v1",
    name: "addReplayReportBounds acceptance-executive-summary",
    covers: [
      "ACCEPTANCE_EXECUTIVE_SUMMARY_PROOF_PATCH (acceptance-executive-summary-proof-v1): a legacy history completes the acceptance gate via the disk-inspect branch (writeArtifactActivity acceptance + inspectArtifactActivity executive-summary/acceptance), recording the executive-summary proof marker without the state-backed acceptance marker.",
      "Branch-specific coverage: current code replays this history through the legacy ACCEPTANCE_EXECUTIVE_SUMMARY_PROOF_PATCH disk-inspect branch because STATE_BACKED_ACCEPTANCE_PROOF_PATCH is absent (patch-ordering invariant).",
    ],
    source: `Controlled Temporal test-workflow history generated by \`${GEN} --branch acceptance-executive-summary\`, which runs a controlled legacy-branch variant of changeWorkflow (current code with the STATE_BACKED_ACCEPTANCE_PROOF_PATCH else-if removed so the preserved disk-inspect branch is exercised; the pre-state-backed code is ~892 commits back and not independently buildable in-repo). Exported with \`${SHOW} --workflow-id adv/change/replay-fixture-project/replayFixtureLegacyAcceptanceExecSummary\`, then sanitized (identity only). No event history hand-authored.`,
  },
  "acceptance-readiness-fence": {
    stem: "fixAcceptanceReadiness.acceptance-readiness-fence",
    workflowId:
      "adv/change/replay-fixture-project/replayFixtureAcceptanceReadinessFence",
    patchMarker: "acceptance-readiness-revision-v1",
    name: "fixAcceptanceReadiness acceptance-readiness-fence",
    covers: [
      "ACCEPTANCE_READINESS_FENCE_PATCH (acceptance-readiness-revision-v1): a new history completes the acceptance gate via the state-backed acceptance proof branch, recording the fence marker, capturing the acceptanceReadinessRevision, and verifying the revision has not changed before applying the gate completion.",
      "Branch-specific coverage: acceptance gate takes the fence path (capture revision, gather state-backed evidence, re-check revision, complete) introduced to prevent stale acceptance-readiness completion.",
    ],
    source: `Controlled Temporal test-workflow history generated by \`${GEN} --branch acceptance-readiness-fence\` against a local dev server, exported with \`${SHOW} --workflow-id adv/change/replay-fixture-project/replayFixtureAcceptanceReadinessFence\`, then sanitized (identity only). No event history hand-authored.`,
  },
  "acceptance-readiness-fence-legacy": {
    stem: "fixAcceptanceReadiness.acceptance-readiness-fence-legacy",
    workflowId:
      "adv/change/replay-fixture-project/replayFixtureAcceptanceReadinessFenceLegacy",
    name: "fixAcceptanceReadiness acceptance-readiness-fence-legacy",
    covers: [
      "ACCEPTANCE_READINESS_FENCE_PATCH (acceptance-readiness-revision-v1) (legacy): a pre-fence history completes the acceptance gate via the state-backed acceptance proof branch without recording the ACCEPTANCE_READINESS_FENCE_PATCH marker.",
      "Branch-specific coverage: current patched code replays this history deterministically through the legacy skip-fence path because the ACCEPTANCE_READINESS_FENCE_PATCH marker is absent.",
    ],
    source: `Controlled Temporal test-workflow history generated by \`${GEN} --branch acceptance-readiness-fence-legacy\` against a local dev server, which runs a controlled legacy-branch variant of changeWorkflow (current code with the acceptance-readiness-fence patch call disabled so the marker is not recorded). Exported with \`${SHOW} --workflow-id adv/change/replay-fixture-project/replayFixtureAcceptanceReadinessFenceLegacy\`, then sanitized (identity only). No event history hand-authored.`,
  },
};

interface HistoryEvent {
  eventId: string;
  eventType: string;
  markerRecordedEventAttributes?: {
    markerName?: string;
    details?: Record<string, { payloads?: Array<{ data?: string }> }>;
  };
  [key: string]: unknown;
}

function sanitizeIdentity(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sanitizeIdentity);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] =
        k === "identity" && typeof v === "string"
          ? SANITIZED_IDENTITY
          : sanitizeIdentity(v);
    }
    return out;
  }
  return value;
}

function markerPatchId(event: HistoryEvent): string | undefined {
  const details = event.markerRecordedEventAttributes?.details;
  if (!details) return undefined;
  for (const value of Object.values(details)) {
    for (const payload of value.payloads ?? []) {
      if (!payload.data) continue;
      try {
        const decoded = JSON.parse(
          Buffer.from(payload.data, "base64").toString("utf8"),
        ) as { id?: string };
        if (typeof decoded.id === "string") return decoded.id;
      } catch {
        // skip non-JSON payload
      }
    }
  }
  return undefined;
}

async function finalize(branch: BranchId, rawPath: string): Promise<void> {
  const config = CONFIGS[branch];
  const history = JSON.parse(await readFile(rawPath, "utf8")) as {
    events: HistoryEvent[];
  };

  let incidentEvent: HistoryEvent;
  if (config.patchMarker) {
    // Locate the MARKER_RECORDED event carrying the target patch id.
    const markerEvent = history.events.find(
      (e) =>
        e.eventType === "EVENT_TYPE_MARKER_RECORDED" &&
        markerPatchId(e) === config.patchMarker,
    );
    if (!markerEvent) {
      throw new Error(
        `[${branch}] no MARKER_RECORDED event with patch id ${config.patchMarker}`,
      );
    }
    incidentEvent = markerEvent;
  } else {
    // Pre-patch legacy histories have no target patch marker; anchor the
    // metadata to the last history event, which is deterministic and replay-stable.
    incidentEvent = history.events[history.events.length - 1];
    if (!incidentEvent) {
      throw new Error(`[${branch}] history has no events`);
    }
  }

  const sanitized = sanitizeIdentity(history) as { events: HistoryEvent[] };

  const historyPath = `${historiesDir}${config.stem}.history.json`;
  const metadataPath = `${historiesDir}${config.stem}.metadata.json`;

  const historyJson = await prettierFormat(JSON.stringify(sanitized), {
    filepath: historyPath,
  });
  await writeFile(historyPath, historyJson, "utf8");

  const metadata = {
    name: config.name,
    workflowType: "changeWorkflow",
    workflowId: config.workflowId,
    source: config.source,
    covers: config.covers,
    expected:
      "Worker.runReplayHistory resolves against the current workflow bundle.",
    sanitized: true,
    eventCount: sanitized.events.length,
    incidentEventId: incidentEvent.eventId,
    incidentEventType: incidentEvent.eventType,
    patchMarker: config.patchMarker,
  };
  const metadataJson = await prettierFormat(JSON.stringify(metadata), {
    filepath: metadataPath,
  });
  await writeFile(metadataPath, metadataJson, "utf8");

  console.log(
    JSON.stringify(
      {
        branch,
        historyPath,
        metadataPath,
        eventCount: sanitized.events.length,
        incidentEventId: incidentEvent.eventId,
        patchMarker: config.patchMarker,
      },
      null,
      2,
    ),
  );
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.includes("--all")) {
    for (const branch of Object.keys(CONFIGS) as BranchId[]) {
      await finalize(branch, `/tmp/${rawName(branch)}.history.raw.json`);
    }
    return;
  }
  const branch = args[args.indexOf("--branch") + 1] as BranchId;
  const raw = args[args.indexOf("--raw") + 1];
  if (!branch || !(branch in CONFIGS) || !raw) {
    throw new Error(
      "Usage: finalize-replay-fixture.ts --branch <id> --raw <path> | --all",
    );
  }
  await finalize(branch, raw);
}

function rawName(branch: BranchId): string {
  return {
    "state-backed-gate-artifact": "pathA",
    "state-backed-acceptance": "pathB",
    "acceptance-executive-summary": "pathC",
    "acceptance-readiness-fence": "pathD",
    "acceptance-readiness-fence-legacy": "pathE",
  }[branch];
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
