import { describe, expect, it } from "vitest";
import { execSync } from "child_process";

/**
 * Denylist test: ensure retired project-workflow (PSW) symbols do not
 * re-enter the source tree. Catches copy-paste revivals and stale imports.
 *
 * Permitted references:
 *   - "projectWorkflow" in comments documenting retirement
 *   - "ProjectWorkflowState" in comments documenting retirement
 *   - File paths containing "project-workflow" (the files themselves were deleted)
 *
 * Blocked references:
 *   - Imports of deleted PSW modules
 *   - Function/type definitions using PSW names
 *   - Live code paths referencing PSW symbols
 */
describe("PSW retirement denylist", () => {
  const deniedPatterns = [
    // Deleted helper/module imports
    {
      regex: /import.*project-workflow-helper/,
      desc: "import of deleted project-workflow-helper",
    },
    {
      regex: /from.*project-workflow-helper/,
      desc: "import source project-workflow-helper",
    },
    // Live code references to PSW functions/types (not comments)
    {
      regex: /\bgetBoundedProjectWorkflowAccess\b/,
      desc: "getBoundedProjectWorkflowAccess symbol",
    },
    {
      regex: /\bbuildProjectWorkflowId\b/,
      desc: "buildProjectWorkflowId symbol",
    },
    {
      regex: /\brebuildProjectWorkflowState\b/,
      desc: "rebuildProjectWorkflowState symbol",
    },
    {
      regex: /\bensureProjectWorkflowStarted\b/,
      desc: "ensureProjectWorkflowStarted symbol",
    },
    { regex: /\brepairChangeActivity\b/, desc: "repairChangeActivity symbol" },
    {
      regex: /\bapplyChangeSummarySignal\b/,
      desc: "applyChangeSummarySignal symbol",
    },
    {
      regex: /\baddProjectWisdomUpdate\b/,
      desc: "addProjectWisdomUpdate symbol",
    },
    {
      regex: /\bpurgeChangeSummaryUpdate\b/,
      desc: "purgeChangeSummaryUpdate symbol",
    },
    {
      regex: /\brecordMigrationEntryUpdate\b/,
      desc: "recordMigrationEntryUpdate symbol",
    },
    {
      regex: /\baddWorktreeSessionUpdate\b/,
      desc: "addWorktreeSessionUpdate symbol",
    },
    {
      regex: /\bremoveWorktreeSessionUpdate\b/,
      desc: "removeWorktreeSessionUpdate symbol",
    },
  ];

  it("has no live PSW references in src/", () => {
    // Get all .ts files under src/ except tests and generated files
    const files = execSync(
      "git ls-files src/**/*.ts | grep -v '.test.ts' | grep -v '.d.ts' | grep -v 'workflows-autogenerated'",
      { cwd: process.cwd(), encoding: "utf-8" },
    )
      .trim()
      .split("\n")
      .filter(Boolean);

    const violations: string[] = [];

    for (const file of files) {
      const content = execSync(`cat "${file}"`, {
        cwd: process.cwd(),
        encoding: "utf-8",
      });

      for (const { regex, desc } of deniedPatterns) {
        // Check each line; skip pure comment lines that document retirement
        for (const line of content.split("\n")) {
          const trimmed = line.trim();
          // Allow comments that explicitly mention "retired" or "deleted"
          if (trimmed.startsWith("//") || trimmed.startsWith("*")) {
            if (
              trimmed.includes("retired") ||
              trimmed.includes("deleted") ||
              trimmed.includes("no longer") ||
              trimmed.includes("was removed")
            ) {
              continue;
            }
          }
          if (regex.test(line)) {
            violations.push(`${file}: ${desc}\n  ${line.trim()}`);
          }
        }
      }
    }

    if (violations.length > 0) {
      expect.fail(
        `Found ${violations.length} live PSW reference(s):\n\n${violations.join("\n\n")}`,
      );
    }
  });
});
