/**
 * Ops Evidence Append Tool
 *
 * Appends a typed operational evidence entry to a change's ops_followup profile
 * and updates the child profile status. Evidence is append-only; existing
 * entries are never overwritten. Structural fields (id, recorded_at) are
 * generated by the tool so callers cannot fabricate them.
 */

import { z } from "zod";
import { nanoid } from "nanoid";
import type { Store } from "../storage/store-types";
import { getService } from "../temporal/service";
import { getProjectId } from "../utils/project-id";
import { formatToolOutput } from "../utils/tool-output";
import { opsEvidenceAppendedSignal } from "../temporal/messages";
import { fireSignalAndRefresh, getChangeHandle } from "./_adapters";
import {
  type OpsEvidenceEntry,
  type OpsFollowupStatus,
  type Change,
} from "../types";

const OPS_EVIDENCE_TOOL_STATUS = [
  "partial",
  "failed",
  "rerun_needed",
  "rollback_needed",
  "cleanup_needed",
  "complete",
] as const;

type OpsEvidenceToolStatus = (typeof OPS_EVIDENCE_TOOL_STATUS)[number];

const OpsEvidenceToolStatusSchema = z.enum(OPS_EVIDENCE_TOOL_STATUS);

const ENTRY_STATUS_MAP: Record<
  OpsEvidenceToolStatus,
  OpsEvidenceEntry["status"]
> = {
  partial: "partial",
  failed: "fail",
  rerun_needed: "rerun_needed",
  rollback_needed: "rollback_needed",
  cleanup_needed: "cleanup_needed",
  complete: "complete",
};

const PROFILE_STATUS_MAP: Record<OpsEvidenceToolStatus, OpsFollowupStatus> = {
  partial: "partial",
  failed: "failed",
  rerun_needed: "rerun_needed",
  rollback_needed: "rollback_needed",
  cleanup_needed: "cleanup_needed",
  complete: "complete",
};

interface AddEvidenceInput {
  changeId: string;
  env: string;
  action: string;
  status: OpsEvidenceToolStatus;
  summary: string;
  batch?: string;
  next_step?: string;
  completion_signal?: string;
  dryRun?: boolean;
}

async function getChangeHandleForChangeId(
  store: Store,
  changeId: string,
): Promise<ReturnType<typeof getChangeHandle>> {
  const bundle = getService();
  if (!bundle) throw new Error("Temporal service not available");
  const projectId =
    store.productContext?.productProjectId ??
    (await getProjectId(store.paths.root));
  if (!projectId) throw new Error("Could not resolve project ID");
  return getChangeHandle(bundle.client, projectId, changeId);
}

export const opsEvidenceTools = {
  adv_ops_evidence_add: {
    description:
      "Append operational evidence to a change's ops_followup profile and update the child profile status. " +
      "Evidence is append-only and records the environment, action, result status, and summary.",
    args: {
      changeId: z
        .string()
        .min(1)
        .describe("Change ID that owns the ops_followup profile."),
      env: z
        .string()
        .min(1)
        .describe("Environment where the action ran (e.g. prod, staging, ci)."),
      action: z
        .string()
        .min(1)
        .describe("Action or command that was executed."),
      status: OpsEvidenceToolStatusSchema.describe(
        "Operational status of the follow-up after this evidence. Maps to both the evidence entry status and the profile status.",
      ),
      summary: z
        .string()
        .min(1)
        .describe("Human-readable summary of the result."),
      batch: z.string().optional().describe("Optional batch/run identifier."),
      next_step: z
        .string()
        .optional()
        .describe("Optional next step or remediation note."),
      completion_signal: z
        .string()
        .optional()
        .describe(
          "Optional signal that will indicate completion (e.g. PR merge, deployment finish).",
        ),
      dryRun: z
        .boolean()
        .optional()
        .describe("When true, returns a preview without appending evidence."),
    },
    execute: async (input: AddEvidenceInput, store: Store): Promise<string> => {
      const load = await store.changes.get(input.changeId);
      if (!load.success || !load.data) {
        return formatToolOutput({
          error: `Change not found: ${input.changeId}`,
        });
      }

      const change = load.data as Change;
      if (!change.ops_followup) {
        return formatToolOutput({
          error: `Change ${input.changeId} has no ops_followup profile. Promote or seed an ops follow-up before appending evidence.`,
          code: "NO_OPS_FOLLOWUP_PROFILE",
        });
      }

      const recordedAt = new Date().toISOString();
      const entry: OpsEvidenceEntry = {
        id: `oee-${nanoid(12)}`,
        recorded_at: recordedAt,
        env: input.env,
        action: input.action,
        status: ENTRY_STATUS_MAP[input.status],
        summary: input.summary,
        ...(input.batch ? { batch: input.batch } : {}),
        ...(input.next_step ? { next_step: input.next_step } : {}),
        ...(input.completion_signal
          ? { completion_signal: input.completion_signal }
          : {}),
      };

      const profileStatus = PROFILE_STATUS_MAP[input.status];
      const priorCount = (change.ops_followup.evidence ?? []).length;

      if (input.dryRun) {
        return formatToolOutput({
          success: true,
          dryRun: true,
          changeId: input.changeId,
          entry,
          status: profileStatus,
          evidence_count: priorCount,
        });
      }

      const handle = await getChangeHandleForChangeId(store, input.changeId);
      await fireSignalAndRefresh(
        handle,
        store,
        input.changeId,
        opsEvidenceAppendedSignal,
        {
          entry,
          status: profileStatus,
          appendedAt: recordedAt,
        },
      );

      return formatToolOutput({
        success: true,
        changeId: input.changeId,
        entry,
        status: profileStatus,
        evidence_count: priorCount + 1,
      });
    },
  },
};
