/**
 * Work-graph types — structural dependency graph + resume projection.
 *
 * Owns the canonical node reference shape, resume projection schema, and typed
 * error results for edge validation. Edge fields (`blocked_by` on
 * EpicShellEntrySchema, `same_project_dependencies` on ChangeSchema) live on
 * their respective domain schemas and reference WorkNodeRefSchema defined here.
 *
 * rq-workGraphTypes01 (addDependencyAwareResume): additive schema, default []
 * on every edge field, no migration.
 */
import { z } from "zod";

// =============================================================================
// WorkNodeRef — canonical reference to a node in the work graph
// =============================================================================

/**
 * Discriminated reference to either an Epic shell/change entry or an active
 * change. A change linked into an Epic is ONE canonical change node; its Epic
 * entry is display/membership metadata, not a second graph node.
 */
export const WorkNodeRefSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("epic_entry"),
    epic_id: z.string().min(1),
    entry_id: z.string().min(1),
  }),
  z.object({
    kind: z.literal("change"),
    project_id: z.string().regex(/^[0-9a-f]{40}$/),
    change_id: z.string().min(1),
  }),
]);
export type WorkNodeRef = z.infer<typeof WorkNodeRefSchema>;

// =============================================================================
// Resume projection
// =============================================================================

export const ResumeRowLifecycleSchema = z.enum([
  /** Epic shell with all prereqs terminal, not yet promoted to a workflow-backed change. */
  "ready_to_promote",
  /** Active change with all prereqs terminal, no in_progress tasks yet. */
  "ready_to_start",
  /** Currently being worked (has in_progress tasks). */
  "active",
  /** Has at least one non-terminal hard prerequisite. */
  "blocked",
  /** Terminal (archived/closed). */
  "done",
]);
export type ResumeRowLifecycle = z.infer<typeof ResumeRowLifecycleSchema>;

export const ResumeRowKindSchema = z.enum(["epic_shell", "change"]);
export type ResumeRowKind = z.infer<typeof ResumeRowKindSchema>;

/**
 * Single row in the resume projection. `blockers` lists the non-terminal
 * prerequisites (empty when lifecycle is ready/done).
 */
export const ResumeRowSchema = z.object({
  node: WorkNodeRefSchema,
  title: z.string(),
  kind: ResumeRowKindSchema,
  lifecycle: ResumeRowLifecycleSchema,
  /** Lower = earlier in advisory order (Epic order, then entry order). */
  advisory_rank: z.number(),
  /** Non-terminal prerequisites; empty for ready/done rows. */
  blockers: z.array(WorkNodeRefSchema).default([]),
  /** Epic id that owns this row, when applicable. */
  source_epic_id: z.string().optional(),
  /** Epic id this row redirects to (cross-Epic blocker), when applicable. */
  target_epic_id: z.string().optional(),
});
export type ResumeRow = z.infer<typeof ResumeRowSchema>;

/**
 * Cross-Epic redirect: source Epic's next actionable item is blocked by a node
 * in target Epic. Emitted instead of falsely marking the source Epic stalled.
 */
export const CrossEpicRedirectSchema = z.object({
  source_epic_id: z.string(),
  target_epic_id: z.string(),
  /** The node in target_epic_id that is blocking progress. */
  blocker_node: WorkNodeRefSchema,
  /** The node in source_epic_id that is blocked. */
  blocked_node: WorkNodeRefSchema,
});
export type CrossEpicRedirect = z.infer<typeof CrossEpicRedirectSchema>;

/**
 * Diagnostics surface legacy/partial state without failing the read.
 * `cycles` reports any cycles discovered in the persisted graph (should be
 * impossible post-validation, but defensive for legacy/manual state).
 * `unresolved_refs` reports edges pointing at nodes not in scope.
 */
export const WorkGraphDiagnosticsSchema = z.object({
  cycles: z.array(z.array(WorkNodeRefSchema)).default([]),
  unresolved_refs: z.array(WorkNodeRefSchema).default([]),
});
export type WorkGraphDiagnostics = z.infer<typeof WorkGraphDiagnosticsSchema>;

/**
 * Full resume projection. Generated by a pure-read kernel (no signal fired,
 * no state mutation); `diagnostics` degrades gracefully on legacy state.
 */
export const ResumeProjectionSchema = z.object({
  generated_at: z.string(),
  scope: z.object({
    project_id: z.string().regex(/^[0-9a-f]{40}$/),
    epic_ids: z.array(z.string()).optional(),
  }),
  /**
   * First node by advisory rank that is not done (may be blocked). This is the
   * complete cross-Epic ordering authority; Epic.progress.next_entry_id is only
   * a workflow-local advisory approximation.
   */
  ordered_next: ResumeRowSchema.nullable(),
  /** Unblocked, not-done, not-active nodes ready to be picked up. */
  actionable: z.array(ResumeRowSchema),
  /** Nodes with at least one non-terminal hard prerequisite. */
  blocked: z.array(ResumeRowSchema),
  /** Nodes currently being worked (in_progress tasks). */
  active: z.array(ResumeRowSchema),
  /** Cross-Epic blockers surfaced as redirects. */
  redirects: z.array(CrossEpicRedirectSchema),
  /** Legacy/partial state diagnostics; never fails the read. */
  diagnostics: WorkGraphDiagnosticsSchema,
});
export type ResumeProjection = z.infer<typeof ResumeProjectionSchema>;

// =============================================================================
// Typed error results — returned by work-graph validation (Task C)
// =============================================================================

/**
 * Cycle detected when adding an edge. `cycle_path` is the CLOSED form
 * `[A,B,A]` (cycle-closing node repeated) for unambiguous diagnostics.
 */
export const DependencyCycleErrorSchema = z.object({
  code: z.literal("DEPENDENCY_CYCLE"),
  cycle_path: z.array(WorkNodeRefSchema),
});
export type DependencyCycleError = z.infer<typeof DependencyCycleErrorSchema>;

/**
 * Edge target does not resolve to a same-project node in scope.
 */
export const UnresolvedDependencyErrorSchema = z.object({
  code: z.literal("UNRESOLVED_DEPENDENCY"),
  ref: WorkNodeRefSchema,
});
export type UnresolvedDependencyError = z.infer<
  typeof UnresolvedDependencyErrorSchema
>;

/**
 * Malformed edge: self-edge, duplicate ref, or otherwise invalid WorkNodeRef.
 */
export const InvalidWorkNodeRefErrorSchema = z.object({
  code: z.literal("INVALID_WORK_NODE_REF"),
  reason: z.enum(["self_edge", "duplicate_ref", "malformed"]),
  ref: WorkNodeRefSchema.optional(),
});
export type InvalidWorkNodeRefError = z.infer<
  typeof InvalidWorkNodeRefErrorSchema
>;

/**
 * Shell promotion refused because same-project prerequisites are nonterminal.
 * Emitted by `adv_epic_add_shell` / `adv_epic_promote_shell` (D3 enforcement).
 */
export const ShellPrereqNonterminalErrorSchema = z.object({
  code: z.literal("SHELL_PREREQ_NONTERMINAL"),
  blocking_refs: z.array(WorkNodeRefSchema),
});
export type ShellPrereqNonterminalError = z.infer<
  typeof ShellPrereqNonterminalErrorSchema
>;

/**
 * Change creation refused because same-project prerequisites are nonterminal.
 * Emitted by `adv_change_create` (D3 enforcement).
 */
export const DepPrereqNonterminalErrorSchema = z.object({
  code: z.literal("DEP_PREREQ_NONTERMINAL"),
  blocking_refs: z.array(WorkNodeRefSchema),
});
export type DepPrereqNonterminalError = z.infer<
  typeof DepPrereqNonterminalErrorSchema
>;
